define("./ocx_preview",["./active_x"],function(f){var e={},d={};return f("./active_x").extend({ocxNotInstall:!1,params:null,constructor:function(a){this.base(a,["hikui-active"],[])},render:function(){this.base("clsid:E55C9850-D54F-4DF2-A7B4-B8C3B687BE2F");try{var a=location.href;a.indexOf("http://")==0?a=a.substring(7):a.indexOf("https://")==0&&(a=a.substring(8));var a=a.substring(0,a.indexOf("/")),b=this.ocxEl[0].AddSecuriteZone(a);("false"==b||!1==b)&&jAlert("\u5f53\u524d\u5730\u5740\u672a\u88ab\u52a0\u5165\u4fe1\u4efb\u7ad9\u70b9\u3002\u8bf7\u5c06\u5f53\u524d\u5730\u5740\u52a0\u5165\u4fe1\u4efb\u7ad9\u70b9\uff0c\u7136\u540e\u5728\u5237\u65b0\u672c\u9875\u9762\u3002")}catch(c){}this.ocxEl[0].StopPreview()},
addIndexCodeMap:function(a,b,c){c!=null&&(d[a]==null&&(d[a]=[]),d[a].push(c),e[c]=b)},removeIndexCodeMap:function(a){var b=d[a];if(b!=null){var c=null;b.length>0&&(c=b[b.length-1],b.pop());d[a].length<1&&(d[a]=null);c!=null&&(e[c]=null)}},getIndexCodeMap:function(a){return e[a]},SetVagServerInfo:function(a,b){this.ocxEl[0].SetVagServerInfo(a,b)},SetWindowId:function(a){this.ocxEl[0].SetWindowId(a)},StartPreview:function(a){this.ocxEl[0].StartPreview(a)},StartPreviewEx:function(a){this.ocxEl[0].StartPreviewEx(a)},
StopPreview:function(){this.ocxEl[0].StopPreview()},SetPerCfgInfo:function(a){this.ocxEl[0].SetPerCfgInfo(a)},SetToolBar:function(a){this.ocxEl[0].SetToolBar(a)},Set3DZoomMode:function(a){this.ocxEl[0].Set3DZoomMode(a)},SetVideoParam:function(a,b,c,d){this.ocxEl[0].SetVideoParam(a,b,c,d)},GetVideoParam:function(){return this.ocxEl[0].GetVideoParam()},SnapShot:function(a,b){this.ocxEl[0].SnapShot(a,b)},StartRecord:function(){this.ocxEl[0].StartRecord()},StopRecord:function(){this.ocxEl[0].StopRecord()},
OpenFolder:function(a){return this.ocxEl[0].OpenFolder(a)},OpenFile:function(a,b,c){return this.ocxEl[0].OpenFile(a,b,c)},SetRecordParam:function(a){this.ocxEl[0].SetRecordParam(a)},SetSnapParam:function(a){this.ocxEl[0].SetSnapParam(a)},SetOverLapMode:function(a){this.ocxEl[0].SetSnapParam(a)},SetAutoSize:function(a){this.ocxEl[0].SetAutoSize(a)},SetToken:function(a,b){this.ocxEl[0].SetToken(a,b)},SetEncrypt:function(a){this.ocxEl[0].SetEncrypt(a)},SetToolBarAlwaysShow:function(a){this.ocxEl[0].SetToolBarAlwaysShow(a)},
SetInstPlayCfg:function(a){this.ocxEl[0].SetInstPlayCfg(a)},SetRightCode:function(a){try{this.ocxEl[0].SetRightCode(a)}catch(b){}},SetSnapMultiType:function(a){try{this.ocxEl[0].SetSnapMultiType(a)}catch(b){}},SetDecode:function(a){try{this.ocxEl[0].SetDecode(a)}catch(b){}},PlaySound:function(a){try{this.ocxEl[0].PlaySound(a)}catch(b){}},EnterFishEye:function(){try{this.ocxEl[0].EnterFishEye()}catch(a){}},ExitFishEye:function(){try{this.ocxEl[0].ExitFishEye()}catch(a){}},SetLayoutType:function(a){try{this.ocxEl[0].SetLayoutType(a)}catch(b){}},
SetFishEyeParam:function(a){try{this.ocxEl[0].SetFishEyeParam(a)}catch(b){}},GetFishEyeParam:function(){try{return this.ocxEl[0].GetFishEyeParam()}catch(a){}},GetVersion:function(){try{return this.ocxEl[0].GetVersion()}catch(a){}},GetDirectoryPath:function(){try{var a=this.ocxEl[0].GetDirectoryPath();if(a=="null"||a==null)return null;if(a[a.length-1]=="\\")return a;return a+"\\"}catch(b){return null}},GetSystemDrive:function(){try{return this.ocxEl[0].GetSystemDrive()+":"}catch(a){return"c:"}},GetUserDocument:function(){try{return this.ocxEl[0].GetUserDocument()}catch(a){return"C:\\Program Data"}},
EnableMenu:function(a){try{this.ocxEl[0].EnableMenu(a)}catch(b){}},SetBarVisible:function(a){try{this.ocxEl[0].SetBarVisible(a)}catch(b){}},getOcxUrl:function(){return pt.ctx+"/web/softs/HIKOCX.CAB"},NotifyBSEvent:function(a){this.ocxEl[0].NotifyBSEvent(a)},checkFile:function(a){var b=null;window.XMLHttpRequest?b=new XMLHttpRequest:window.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));if(b!=null){if(b.open("GET",a,!1),b.send(),b.readyState==4&&b.status==404)return!1}else jAlert("\u60a8\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301XMLHTTP,\u68c0\u67e5\u6587\u4ef6\u5931\u8d25!");
return!0},handleException:function(){var a=this.checkFile(this.getOcxUrl()),b=this.msgEl||this.el;this.ocxEl!=null&&this.ocxEl.hide();b.find('div[msgType="msg"]').remove();b.find("*").hide();a?b.append('<div class="msg-b msg-b-stop"><i></i><div class="msg-cnt"><span>\u63a7\u4ef6\u5f02\u5e38\uff01</span></div></div>'):b.append('<div class="msg-b msg-b-stop"><i></i><div class="msg-cnt"><span>\u63a7\u4ef6\u5f02\u5e38\uff01</span><p>\u63a7\u4ef6\u4e0d\u5b58\u5728\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458\u4e0a\u4f20\u63a7\u4ef6</p></div></div>');
a&&this.msgEl&&this.msgEl.length>0&&(typeof currentIsDialog=="undefined"||currentIsDialog==!1)?(loader.show("\u6700\u65b0\u63a7\u4ef6\u6b63\u5728\u52a0\u8f7d\u4e2d\uff0c\u8bf7\u7a0d\u540e...\uff08\u52a0\u8f7d\u5931\u8d25\u8bf7\u8df3\u8f6c\u5230\u9996\u9875\u8fdb\u884c\u624b\u52a8\u4e0b\u8f7d\u548c\u5b89\u88c5\uff09"),setTimeout(function(){loader.hide();jAlert("\u52a0\u8f7d\u63a7\u4ef6\u5931\u8d25\uff0c\u8bf7\u8df3\u8f6c\u5230\u9996\u9875\u8fdb\u884c\u624b\u52a8\u4e0b\u8f7d\u548c\u5b89\u88c5\u3002")},
15E3)):b.find(".msg-b-stop").loading("show",{text:"\u52a0\u8f7d\u4e2d",size:"m",overlay:!1});return!1}})});
